/* Checksum.ai autogenerated test */
import { test as base } from "@playwright/test"
import { init, IChecksumPage } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init(base)

test(
  defineChecksumTest("Delete a product from the product row", "22Y0K"),
  async ({ page }: { page: IChecksumPage }) => {
    await login(page)
    await page.goto("/a/products", { waitUntil: "domcontentloaded" })

    await checksumAI(
      "Click on the 'More options' button for the first product in the product table to open the menu.",
      () =>
        page
          .checksumSelector("SqoiO")
          .getByRole("row", { name: "Non-Alcoholic Concentrated" })
          .getByRole("button")
          .click()
    )

    await expect(
      page.getByText("Delete", { exact: true }),
      "Delete option should appear in the product options menu"
    ).toBeVisible()

    await checksumAI(
      "Click on the 'Delete' button in the product options menu.",
      () =>
        page
          .checksumSelector("hj3QE")
          .getByRole("button", { name: "Delete" })
          .click()
    )

    await expect(
      page.getByText("Are you sure you want to delete this product?", {
        exact: true,
      }),
      "Delete confirmation dialog should appear"
    ).toBeVisible()

    await expect(
      page.getByText("Yes, confirm", { exact: true }),
      "Confirmation button should appear in the delete dialog"
    ).toBeVisible()

    await expect(
      page.getByText("Cancel", { exact: true }),
      "Cancel button should appear in the delete dialog"
    ).toBeVisible()

    await checksumAI(
      "Click on the 'Yes, confirm' button to confirm the deletion of the product.",
      () =>
        page
          .checksumSelector("1IB4m")
          .getByRole("button", { name: "Yes, confirm" })
          .click()
    )

    await expect(
      page.getByText("Are you sure you want to delete this product?", {
        exact: true,
      }),
      "Delete confirmation dialog should close"
    ).not.toBeVisible()

    await expect(
      page.getByText("Yes, confirm", { exact: true }),
      "'Yes, confirm' button should disappear after confirming deletion"
    ).not.toBeVisible()

    await expect(
      page.getByText("1 - 15 of 29 Products", { exact: true }),
      "Product list count should update to reflect deletion"
    ).toBeVisible()
  }
)
