/* Checksum.ai autogenerated test */
import { test as base } from "@playwright/test"
import { init, IChecksumPage } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init(base)

test(
  defineChecksumTest("Edit the general information of a product", "VOt3u"),
  async ({ page }: { page: IChecksumPage }) => {
    await login(page)
    await page.goto("/a/products", { waitUntil: "domcontentloaded" })

    await checksumAI("Click on 'More options' for the first product", () =>
      page
        .checksumSelector("VWX8x")
        .getByRole("row", { name: "Non-Alcoholic Concentrated" })
        .getByRole("button")
        .click()
    )

    await expect(
      page.getByText("Edit", { exact: true }),
      "Options menu should display 'Edit' option"
    ).toBeVisible()

    await checksumAI(
      "Click on 'Edit' to edit the general information of the product",
      () =>
        page
          .checksumSelector("EDzWx")
          .getByRole("button", { name: "Edit" })
          .click()
    )

    await expect(
      page.getByText("Navigated to Medusa Admin", { exact: true }),
      "Admin section for editing should appear"
    ).toBeVisible()

    await expect(
      page.getByText("Back to Products", { exact: true }),
      "'Back to Products' button should appear indicating edit mode"
    ).toBeVisible()

    await expect(
      page.getByText("Edit", { exact: true }),
      "Edit options should be available"
    ).toBeVisible()

    await expect(
      page.getByText("Published", { exact: true }),
      "Product publication status should be visible"
    ).toBeVisible()

    await expect(
      page.getByText("Subtitle–", { exact: true }),
      "Subtitle field should be present for editing"
    ).toBeVisible()

    await expect(
      page.getByText("DiscountableTrue", { exact: true }),
      "Discountable option should be visible and editable"
    ).toBeVisible()

    await expect(
      page.getByText(
        "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
        { exact: true }
      ),
      "Product title should be visible for editing"
    ).toBeVisible()

    await checksumAI(
      "Click on 'More options' to find the edit mode for the product's general information",
      () =>
        page
          .checksumSelector("hNhWA")
          .locator("div")
          .filter({
            hasText: /^Non-Alcoholic Concentrated Perfume OilPublished$/,
          })
          .getByRole("button")
          .nth(1)
          .click()
    )

    await expect(
      page.getByText("Edit General Information", { exact: true }),
      "'Edit General Information' option should appear"
    ).toBeVisible()

    await checksumAI(
      "Click on 'Edit General Information' to edit the product's details",
      () =>
        page
          .checksumSelector("pOYs6")
          .getByRole("button", { name: "Edit General Information" })
          .click()
    )

    await expect(
      page.getByText("Save", { exact: true }),
      "Save button should appear"
    ).toBeVisible()

    await expect(
      page.getByText("Title *", { exact: true }),
      "Title input field should appear"
    ).toBeVisible()

    await expect(
      page.getByText("Handle *", { exact: true }),
      "Handle input field should appear"
    ).toBeVisible()

    await expect(
      page.getByText(
        "When unchecked discounts will not be applied to this product.",
        { exact: true }
      ),
      "Discountable option description should appear"
    ).toBeVisible()

    await checksumAI("Edit the product subtitle", () =>
      page
        .checksumSelector("FaQdD")
        .getByPlaceholder("Warm and cozy...")
        .fill("A refined scent for all occasions - 1711517458743")
    )

    await checksumAI(
      "Click on 'Save' to save the edited general information",
      () =>
        page
          .checksumSelector("Pva7h")
          .getByRole("button", { name: "Save" })
          .click()
    )

    await expect(
      page.getByText("Save", { exact: true }),
      "'Save' button should disappear after saving the product information"
    ).not.toBeVisible()

    await expect(
      page.getByText("Edit General Information", { exact: true }),
      "'Edit General Information' mode should exit after saving changes"
    ).not.toBeVisible()

    await expect(
      page.getByText(
        "SubtitleA refined scent for all occasions - 1711517458743",
        { exact: true }
      ),
      "Edited subtitle should appear with the new value after saving changes"
    ).toBeVisible()

    await expect(
      page.getByText("Product was successfully updated", { exact: true }),
      "Success message should disappear after briefly indicating the product was successfully updated"
    ).not.toBeVisible()

    await checksumAI(
      "Click on 'Back to Products' to navigate back to the list of products",
      () =>
        page
          .checksumSelector("B2pyr")
          .getByRole("button", { name: "Back to Products" })
          .click()
    )

    await expect(
      page.getByText("Back to Products", { exact: true }),
      "'Back to Products' button should disappear after navigation"
    ).not.toBeVisible()

    await expect(
      page.getByText("Import Products", { exact: true }),
      "'Import Products' option should appear on the product list page"
    ).toBeVisible()

    await expect(
      page.getByText("Export Products", { exact: true }),
      "'Export Products' option should appear on the product list page"
    ).toBeVisible()

    await expect(
      page.getByText("New Product", { exact: true }),
      "'New Product' button should appear on the product list page"
    ).toBeVisible()

    await expect(
      page.getByText("1 - 15 of 30 Products", { exact: true }),
      "Product count should appear on the product list page"
    ).toBeVisible()
  }
)
