/* Checksum.ai autogenerated test */
import { test as base } from "@playwright/test"
import { init, IChecksumPage } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init(base)

test(
  defineChecksumTest("Unpublish a product from the product table", "vh3Lz"),
  async ({ page }: { page: IChecksumPage }) => {
    await login(page)
    await page.goto("/a/products", { waitUntil: "domcontentloaded" })

    await checksumAI(
      "Click on 'More options' for the first product to access the unpublish action.",
      () =>
        page
          .checksumSelector("Wy63V")
          .getByRole("row", { name: "Eau De Perfume Spray -" })
          .getByRole("button")
          .click()
    )

    await expect(
      page.getByText("Unpublish", { exact: true }),
      "'Unpublish' option should appear"
    ).toBeVisible()

    await checksumAI(
      "Click on 'Unpublish' to unpublish the first product.",
      () =>
        page
          .checksumSelector("mXHOD")
          .getByRole("button", { name: "Unpublish" })
          .click()
    )

    await expect(
      page.getByText("Unpublish", { exact: true }),
      "'Unpublish' option should disappear after initiating the unpublish action"
    ).not.toBeVisible()

    await expect(
      page.getByText("Draft", { exact: true }),
      "Product status should change to 'Draft' after unpublishing"
    ).toBeVisible()

    await expect(
      page.getByText("Successfully unpublished product", { exact: true }),
      "Success message should appear and then disappear to confirm the product was unpublished"
    ).toBeVisible()

    await expect(
      page.getByText("Successfully unpublished product", { exact: true }),
      "Success message should appear and then disappear to confirm the product was unpublished"
    ).not.toBeVisible()
  }
)
