/* Checksum.ai autogenerated test */
import { init, IVariablesStore } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init()

/*
Things to do:
1. Add a random product name using Date.now() and have the product name include "cktest" to ensure we know it's created by one of our tests. (https://docs.google.com/document/d/1N9XNM8iKTVgUSnRV2ARGi_6lpVo3f2FCaa9pJ_GMU6Q/edit#heading=h.uhj7izteq3od)
2. Save the product name to a variable using the variableStore. Navigate to the product page and verify the product name matches the variable. (https://docs.google.com/document/d/1N9XNM8iKTVgUSnRV2ARGi_6lpVo3f2FCaa9pJ_GMU6Q/edit#heading=h.t045htr4v6ra)
3. Verify the product details match the values used during creation.


When you are done - Experience Checksum Autohealing features
1. Read about auto healing features in the /admin-frontend/checksum/README.md
2. Break the New Product Button Selector. Run the test and see how it autoheals.
3. Remove the New Product Button action and see how Checksum auto heals it
4. Turn off all auto healing features and run the test again. See how the test fails.
5. NOTE: sometimes it's better to turn off auto healing features when editing a test. Makes it easier to spot the changes you need to make.
*/

test(
  defineChecksumTest("Add a product", "78eGZ"),
  async ({
    page,
    variablesStore,
  }: {
    page
    variablesStore: IVariablesStore
  }) => {
    await login(page)
    
    await expect(
      page.getByText("Welcome back! It's great to see you"),
      "Verify we're not on login page anymore"
    ).not.toBeVisible({ timeout: 25000 })
    
    await test.step("Navigate to products page", async () => {
      await checksumAI("Navigate to products page", () =>
        page.goto("/a/products", { waitUntil: "domcontentloaded" })
      )
      
      await expect(
        page.getByRole("button", { name: "New Product" }),
        "Verify the New Product button is visible on products page"
      ).toBeVisible({ timeout: 25000 })
    })
    
    await test.step("Create new product form", async () => {
      await checksumAI("Click on new product button", () =>
        page
          .getByRole("button", { name: "New Product" })
          .click()
      )
    })
    
    await test.step("Fill product details", async () => {
      variablesStore.titleValue = `cktest-${Date.now()}`
      await checksumAI("Fill product title field with cktest product name", () =>
        page.getByPlaceholder("Winter Jacket").fill(variablesStore.titleValue)
      )
      
      variablesStore.subtitleValue = `cktest-${Date.now()}-Fleece Winter Jacket keeps you warm and cozy`
      await checksumAI("Fill product subtitle field with descriptive text", () =>
        page.getByPlaceholder("Warm and cozy...").fill(variablesStore.subtitleValue)
      )
      
      variablesStore.descriptionValue = `cktest-${Date.now()}-This is a fleece winter jacket that keeps you warm and cozy`
      await checksumAI("Fill product description field with detailed information", () =>
        page.getByPlaceholder("A warm and cozy jacket...").fill(variablesStore.descriptionValue)
      )
    })
    
    await test.step("Publish product and return to list", async () => {
      await checksumAI("Click Publish product button to publish the product", () =>
        page.getByRole("button", { name: "Publish product" }).click()
      )
      
      await checksumAI("Click Back to Products button to return to products list", () =>
        page.getByRole("button", { name: "Back to Products" }).click()
      )
      
      await expect(
        page.getByRole("button", { name: "New Product" }),
        "Verify we're back on the products list page"
      ).toBeVisible({ timeout: 25000 })
    })
    
    await test.step("Verify product in products list", async () => {
      await expect(
        page.getByText(variablesStore.titleValue),
        "Verify the created product name is visible in the products table"
      ).toBeVisible({ timeout: 25000 })
    })
    
    await test.step("Navigate to product details page", async () => {
      await checksumAI("Click on the created product row to navigate to product details", () =>
        page.locator('tbody tr').filter({ hasText: variablesStore.titleValue }).click()
      )
    })
    
    await test.step("Verify product details on product page", async () => {
      await expect(
        page.getByRole("heading", { name: variablesStore.titleValue }),
        "Verify the product title heading matches what we created"
      ).toBeVisible()
      
      await expect(
        page.getByText(variablesStore.subtitleValue),
        "Verify the product subtitle matches what we created"
      ).toBeVisible()
      
      await expect(
        page.getByText(variablesStore.descriptionValue),
        "Verify the product description matches what we created"
      ).toBeVisible()
    })
  }
)