/* Checksum.ai autogenerated test */
import { init, IVariablesStore } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init()

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Publish a product but before you do create an API for adding it by first using the network tab to figure out the structure of the API call when creating a new product and then using that API to create the product in the test
2. Verify the product was created successfully by checking the response from the API and by checking the product appears on the page using playwright assertions
3. Later, delete the product using an API call
4. Implement page.waitForResponse() to wait for a network response when Clicking to publish the product. Recommend referencing either the Checksum Playbook or playwright.dev for additional help.
*/

test(
  defineChecksumTest("Create and delete a product using an API", "2K13x"),
  async ({ page, variablesStore }: { page; variablesStore: IVariablesStore }) => {
    await login(page)
    
    await expect(
      page.getByText("Welcome back! It's great to see you"),
      "Verify we're not on login page anymore"
    ).not.toBeVisible({ timeout: 15000 })
    
    await test.step("Create a new product using the API", async () => {
      const productData = {
        title: `cktest-${Date.now()}`,
        subtitle: `cktest-${Date.now()}-api-subtitle`,
        description: `cktest-${Date.now()}-api-description`,
        status: "draft" 
      }
      
      const response = await checksumAI("Create product using API call", () =>
        page.request.post("http://localhost:9000/admin/products", {
          data: productData,
          headers: {
            "Content-Type": "application/json"
          }
        })
      )
      
      await expect(response.status(), "Verify product creation API call succeeded").toBe(200)
      const responseData = await response.json()
      await expect(responseData.product.title, "Verify product title in API response matches what we sent").toBe(productData.title)
      variablesStore.productId = responseData.product.id
      variablesStore.productTitle = productData.title
    })
    
    await test.step("Navigate to products page and verify product appears", async () => {
      await checksumAI("Navigate to products page", () =>
        page.goto("/a/products", { waitUntil: "domcontentloaded" })
      )
      
      await expect(
        page.getByRole("button", { name: "New Product" }),
        "Verify the New Product button is visible on products page"
      ).toBeVisible({ timeout: 25000 })
      
      // Wait for products table to load
      await expect(
        page.locator("table"),
        "Verify products table is loaded"
      ).toBeVisible({ timeout: 25000 })
      
      // Wait for table rows to load (not just the table structure)
      await expect(
        page.locator("table tbody tr"),
        "Verify products table has loaded data rows"
      ).toBeVisible({ timeout: 25000 })
      
      // Use search functionality to find the product
      await checksumAI("Search for the API-created product in products list", async () => {
        const searchInput = page.getByPlaceholder("Search")
        await searchInput.fill(variablesStore.productTitle)
        // Wait for search to complete and results to show
        await expect(
          page.getByText(variablesStore.productTitle),
          "Verify search results show the created product"
        ).toBeVisible({ timeout: 25000 })
      })
      
      await expect(
        page.locator(`tr:has-text("${variablesStore.productTitle}")`).getByText("Draft"),
        "Verify the API-created product shows as Draft status initially"
      ).toBeVisible()
    })
    
    await test.step("Publish the product using UI with page.waitForResponse()", async () => {
      await checksumAI("Click on the three dots menu for the created product", () =>
        page.locator(`tr:has-text("${variablesStore.productTitle}")`).locator('button[aria-haspopup="menu"]').click()
      )
      
      await expect(
        page.getByRole("menu"),
        "Verify the dropdown menu is visible"
      ).toBeVisible({ timeout: 25000 })
      
      await checksumAI("Publish product from dropdown and wait for network response", async () => {
        const responsePromise = page.waitForResponse(response => 
          response.url().includes('localhost:9000') && 
          (response.request().method() === 'POST')
        , { timeout: 25000 })
        
        await page.getByRole("menuitem", { name: "Publish" }).click()
        const response = await responsePromise
        await expect(response.status(), "Verify product publish network response succeeded").toBe(200)
      })
    })

    await test.step("Verify product is published in UI", async () => {
      await checksumAI("Refresh products page to see updated status", () =>
        page.reload({ waitUntil: "domcontentloaded" })
      )
      
      await expect(
        page.getByRole("button", { name: "New Product" }),
        "Verify the New Product button is visible after refresh"
      ).toBeVisible({ timeout: 25000 })
      
      // Wait for table rows to load after refresh
      await expect(
        page.locator("table tbody tr"),
        "Verify products table has loaded data rows after refresh"
      ).toBeVisible({ timeout: 15000 })
      
      await checksumAI("Search for the published product in products list", async () => {
        const searchInput = page.getByPlaceholder("Search")
        await searchInput.fill(variablesStore.productTitle)
        // Wait for search to complete and results to show
        await expect(
          page.getByText(variablesStore.productTitle),
          "Verify search results show the published product"
        ).toBeVisible({ timeout: 25000 })
      })
      
      await expect(
        page.locator(`tr:has-text("${variablesStore.productTitle}")`).getByText("Published"),
        "Verify the product shows as Published status after UI publishing"
      ).toBeVisible()
    })
    
    await test.step("Delete the product using API", async () => {
      const response = await checksumAI("Delete product using API call", () =>
        page.request.delete(`http://localhost:9000/admin/products/${variablesStore.productId}`)
      )
      
      await expect(response.status(), "Verify product deletion API call succeeded").toBe(200)
    })
    
    await test.step("Verify product is deleted from the table", async () => {
      await checksumAI("Refresh products page to verify deletion", () =>
        page.reload({ waitUntil: "domcontentloaded" })
      )
      
      await expect(
        page.getByRole("button", { name: "New Product" }),
        "Verify the New Product button is visible after refresh"
      ).toBeVisible({ timeout: 25000 })
      
      // Wait for table rows to load after refresh
      await expect(
        page.locator("table tbody tr"),
        "Verify products table has loaded data rows after refresh"
      ).toBeVisible({ timeout: 25000 })
      
      await checksumAI("Search for the deleted product to verify it's no longer visible", async () => {
        const searchInput = page.getByPlaceholder("Search")
        await searchInput.fill(variablesStore.productTitle)
        // Wait for search to complete and verify no results
        await expect(
          page.getByText(variablesStore.productTitle),
          "Verify search results show no matches for deleted product"
        ).not.toBeVisible({ timeout: 25000 })
      })
    })
  }
)
