/* Checksum.ai autogenerated test */
import { init, IVariablesStore } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init()

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Use regex to choose a product from the table that has cktest in the name so we delete a product that is Checksum (https://docs.google.com/document/d/1N9XNM8iKTVgUSnRV2ARGi_6lpVo3f2FCaa9pJ_GMU6Q/edit#heading=h.f2o54wi0j3kd)
2. Extract using regex (if needed) the product name and store it in a variable (https://docs.google.com/document/d/1N9XNM8iKTVgUSnRV2ARGi_6lpVo3f2FCaa9pJ_GMU6Q/edit#heading=h.t045htr4v6ra)
3. Delete the product
4. Verify the product was deleted by using a regular expression to match the product name.

*/

test(
  defineChecksumTest("Delete a product", "G8RlA"),
  async ({ page, variablesStore }: { page; variablesStore: IVariablesStore }) => {
    await login(page)
    
    await expect(
      page.getByText("Welcome back! It's great to see you"),
      "Verify we're not on login page anymore"
    ).not.toBeVisible({ timeout: 10000 })
    
    await test.step("Navigate to products page and find cktest product", async () => {
      await checksumAI("Navigate to products page", () =>
        page.goto("/a/products", { waitUntil: "domcontentloaded" })
      )
      
      await expect(
        page.getByRole("button", { name: "New Product" }),
        "Verify the New Product button is visible on products page"
      ).toBeVisible({ timeout: 15000 })
      
      // Wait for products table to be populated (not just header)
      await expect.poll(
        async () => await page.locator('tbody tr').filter({ hasText: /^[^NameCollectionStatusAvailabilityInventory]/ }).count(),
        { timeout: 10000 }
      ).toBeGreaterThan(0)
      
      variablesStore.cktestProducts = page.locator('tbody tr').filter({ hasText: new RegExp('cktest', 'i') })
      variablesStore.cktestCount = await variablesStore.cktestProducts.count()
      
      if (variablesStore.cktestCount === 0) {
        await checksumAI("Click on New Product button to create a cktest product for deletion", () =>
          page.getByRole("button", { name: "New Product" }).click()
        )
        
        variablesStore.productToDelete = `cktest-delete-${Date.now()}`
        
        await checksumAI("Fill product title field with cktest product name", () =>
          page.getByPlaceholder("Winter Jacket").fill(variablesStore.productToDelete)
        )
        
        await checksumAI("Fill product subtitle field with description", () =>
          page.getByPlaceholder("Warm and cozy...").fill("Product to be deleted")
        )
        
        await checksumAI("Fill product description field with test description", () =>
          page.getByPlaceholder("A warm and cozy jacket...").fill("This product will be deleted in the test")
        )
        
        await checksumAI("Click on Publish product button to publish the cktest product", () =>
          page.getByRole("button", { name: "Publish product" }).click()
        )
        
        await checksumAI("Click on Back to Products button to return to products list", () =>
          page.getByRole("button", { name: "Back to Products" }).click()
        )
        
        await expect(
          page.getByRole("button", { name: "New Product" }),
          "Verify we're back on the products list page"
        ).toBeVisible({ timeout: 10000 })
      } else {
        variablesStore.cktestProductTexts = await variablesStore.cktestProducts.allTextContents()
        variablesStore.selectedProductText = variablesStore.cktestProductTexts.find(text => text.includes('cktest'))
        
        variablesStore.regexMatch = variablesStore.selectedProductText?.match(new RegExp('cktest[^\\s]*', 'i'))
        if (variablesStore.regexMatch) {
          variablesStore.productToDelete = variablesStore.regexMatch[0]
        } else {
          variablesStore.productToDelete = variablesStore.selectedProductText?.trim() || "cktest-product"
        }
      }
    })
    
    await test.step("Delete the cktest product", async () => {
      variablesStore.productRow = page.locator('tbody tr').filter({ hasText: new RegExp(variablesStore.productToDelete.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') })
      
      await expect(
        variablesStore.productRow,
        "Verify the cktest product is visible in the table before deletion"
      ).toBeVisible()
      
      await checksumAI("Click on three dots menu button for the cktest product row", () =>
        variablesStore.productRow.locator('button[aria-haspopup="menu"]').click()
      )
      
      await expect(
        page.getByRole("menu"),
        "Verify the dropdown menu is visible"
      ).toBeVisible({ timeout: 10000 })
      
      await checksumAI("Click on Delete option from the dropdown menu", () =>
        page.getByRole("menuitem", { name: "Delete" }).click()
      )
      
      await expect(
        page.getByRole("button", { name: "Yes, confirm" }),
        "Verify the confirmation dialog is visible"
      ).toBeVisible({ timeout: 10000 })
      
      await checksumAI("Click on Yes, confirm button to confirm product deletion", () =>
        page.getByRole("button", { name: "Yes, confirm" }).click()
      )
    })
    
    await test.step("Verify product deletion using regex", async () => {
      await expect(
        page.getByRole("button", { name: "New Product" }),
        "Verify we're still on the products page after deletion"
      ).toBeVisible({ timeout: 10000 })
      
      variablesStore.cktestProductsAfterDeletion = page.locator('tbody tr').filter({ hasText: new RegExp(variablesStore.productToDelete.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') })
      
      await expect(
        variablesStore.cktestProductsAfterDeletion,
        "Verify the deleted cktest product is no longer visible in the table"
      ).toHaveCount(0)
      
      await expect(
        page.getByText(new RegExp(variablesStore.productToDelete.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i')),
        "Verify the deleted product name is not visible anywhere on the page"
      ).not.toBeVisible()
    })
  }
)
