/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init()

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Use regex to choose a product from the table that has cktest in the name so we delete a product that is Checksum
2. Extract using regex (if needed) the product name and store it in a variable
3. Delete the product
4. Verify the product was deleted by using a regular expression to match the product name.

*/

test(
  defineChecksumTest("Delete a product", "G8RlA"),
  async ({ page, variablesStore }) => {
    await login(page)
    await page.goto("/", { waitUntil: "domcontentloaded" })
    await checksumAI("Click on products button", () =>
      page
        .checksumSelector("eQtTT")
        .getByRole("link", { name: "Products" })
        .click()
    )
    await checksumAI("Click on a product", () =>
      page
        .checksumSelector("xLAhI")
        .getByRole("cell", { name: "Non-Alcoholic Concentrated" })
        .getByRole("img")
        .click()
    )
    await checksumAI("Click on 3 dot menu next to product name", () =>
      page.checksumSelector("sus9U").locator("#radix-42").click()
    )
    await checksumAI("Click on Delete option", () =>
      page
        .checksumSelector("IH40z")
        .getByRole("button", { name: "Delete" })
        .click()
    )
    await checksumAI("Click on 'Yes, confirm delete'", () =>
      page
        .checksumSelector("LT9Un")
        .getByRole("button", { name: "Yes, confirm" })
        .click()
    )
  }
)
