/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init()

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Make sure there is at least one product in the table that is in draft status and one product that is not in draft status.
2. Filter for draft products and verify only draft products are displayed.
3. Filter for non-draft products and verify only non-draft products are displayed.
4. Use REPL for this test.
*/

test(
  defineChecksumTest("Filter for a product", "Roi2Q"),
  async ({ page, variablesStore }) => {
    await login(page)
    await page.goto("/", { waitUntil: "domcontentloaded" })
    await checksumAI("Click on products", () =>
      page
        .checksumSelector("dilYE")
        .getByRole("link", { name: "Products" })
        .click()
    )

    await checksumAI("Click on Filter button", () =>
      page
        .checksumSelector("IxPkN")
        .getByRole("button", { name: "Filters" })
        .click()
    )
    await checksumAI("Click on status checkbox", () =>
      page
        .checksumSelector("vECUj")
        .getByRole("button", { name: "Status" })
        .click()
    )
    await checksumAI("Click on draft checkbox", () =>
      page.checksumSelector("2sSKi").getByText("draft", { exact: true }).click()
    )
    await checksumAI("Click Apply button", () =>
      page
        .checksumSelector("vctsb")
        .getByRole("button", { name: "Apply" })
        .click()
    )
  }
)
