/* Checksum.ai autogenerated test */
import { init, IVariablesStore } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init()

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Make sure there is at least one product in the table that is in draft status and one product that is not in draft status. (https://docs.google.com/document/d/1N9XNM8iKTVgUSnRV2ARGi_6lpVo3f2FCaa9pJ_GMU6Q/edit#heading=h.wnxktr3rasha)
2. Filter for draft products and verify only draft products are displayed. (https://docs.google.com/document/d/1N9XNM8iKTVgUSnRV2ARGi_6lpVo3f2FCaa9pJ_GMU6Q/edit#heading=h.t045htr4v6ra)
3. Filter for non-draft products and verify only non-draft products are displayed.
4. Use REPL for this test. (https://docs.google.com/document/d/1N9XNM8iKTVgUSnRV2ARGi_6lpVo3f2FCaa9pJ_GMU6Q/edit#heading=h.q2653rt38xj5)
*/

test(
  defineChecksumTest("Filter for a product", "Roi2Q"),
  async ({
    page,
    variablesStore,
  }: {
    page
    variablesStore: IVariablesStore
  }) => {
    await login(page)

    await expect(
      page.getByText("Welcome back! It's great to see you"),
      "Verify we're not on login page anymore"
    ).not.toBeVisible({ timeout: 25000 })

    await test.step("Navigate to products page", async () => {
      await checksumAI("Navigate to products page", () =>
        page.goto("/a/products", { waitUntil: "domcontentloaded" })
      )

      await expect(
        page.getByRole("button", { name: "New Product" }),
        "Verify the New Product button is visible on products page"
      ).toBeVisible({ timeout: 25000 })
    })

    await test.step("Wait for products table to load", async () => {
      await expect(
        page.locator("table"),
        "Verify products table structure is present"
      ).toBeVisible({ timeout: 25000 })

      await expect
        .poll(
          async () => {
            variablesStore.rowCount = await page.locator("tbody tr").count()
            return variablesStore.rowCount
          },
          { timeout: 30000 }
        )
        .toBeGreaterThan(0)
    })

    await test.step(
      "Check for existing products and create if needed",
      async () => {
        variablesStore.existingDraftProducts = page
          .locator("tbody tr")
          .filter({ hasText: "Draft" })
        variablesStore.draftCount = await variablesStore.existingDraftProducts.count()

        variablesStore.existingPublishedProducts = page
          .locator("tbody tr")
          .filter({ hasText: "Published" })
        variablesStore.publishedCount = await variablesStore.existingPublishedProducts.count()

        if (variablesStore.draftCount === 0) {
          variablesStore.draftProductTitle = `cktest-${Date.now()}-Dproduct`

          await checksumAI(
            "Click on New Product button to create a new draft product",
            () => page.getByRole("button", { name: "New Product" }).click()
          )

          await checksumAI(
            "Fill product title field with draft product name",
            () =>
              page
                .getByPlaceholder("Winter Jacket")
                .fill(variablesStore.draftProductTitle)
          )

          await checksumAI(
            "Fill product subtitle field with descriptive text",
            () =>
              page
                .getByPlaceholder("Warm and cozy...")
                .fill(
                  `${variablesStore.draftProductTitle} - Draft product for filter testing`
                )
          )

          await checksumAI(
            "Fill product description field with detailed information",
            () =>
              page
                .getByPlaceholder("A warm and cozy jacket...")
                .fill(
                  `${variablesStore.draftProductTitle} - This product is created in draft status for testing filter functionality`
                )
          )

          await expect(
            page.getByRole("button", { name: "Save as draft" }),
            "Verify Save as draft button is enabled after filling form"
          ).toBeEnabled({ timeout: 25000 })

          await checksumAI(
            "Click Save as draft button to save the product as draft",
            () => page.getByRole("button", { name: "Save as draft" }).click()
          )

          await expect(
            page.getByRole("button", { name: "Back to Products" }),
            "Verify Back to Products button is visible"
          ).toBeVisible({ timeout: 25000 })

          await checksumAI("Navigate back to products", () =>
            page.getByRole("button", { name: "Back to Products" }).click()
          )

          await expect(
            page.getByRole("button", { name: "New Product" }),
            "Verify we're back on the products list page"
          ).toBeVisible({ timeout: 40000 })
        }

        if (variablesStore.publishedCount === 0) {
          variablesStore.publishedProductTitle = `cktest-${Date.now()}-Pproduct`

          await checksumAI(
            "Click on New Product button to create a new published product",
            () => page.getByRole("button", { name: "New Product" }).click()
          )

          await checksumAI(
            "Fill product title field with published product name",
            () =>
              page
                .getByPlaceholder("Winter Jacket")
                .fill(variablesStore.publishedProductTitle)
          )

          await checksumAI(
            "Fill product subtitle field with descriptive text",
            () =>
              page
                .getByPlaceholder("Warm and cozy...")
                .fill(
                  `${variablesStore.publishedProductTitle} - Published product for filter testing`
                )
          )

          await checksumAI(
            "Fill product description field with detailed information",
            () =>
              page
                .getByPlaceholder("A warm and cozy jacket...")
                .fill(
                  `${variablesStore.publishedProductTitle} - This product is created and published for testing filter functionality`
                )
          )

          await expect(
            page.getByRole("button", { name: "Publish product" }),
            "Verify Publish product button is enabled after filling form"
          ).toBeEnabled({ timeout: 25000 })

          await checksumAI(
            "Click Publish product button to publish the product",
            () => page.getByRole("button", { name: "Publish product" }).click()
          )

          await expect(
            page.getByRole("button", { name: "Back to Products" }),
            "Verify Back to Products button is visible"
          ).toBeVisible({ timeout: 25000 })

          await checksumAI("Navigate back to products", () =>
            page.getByRole("button", { name: "Back to Products" }).click()
          )

          await expect(
            page.getByRole("button", { name: "New Product" }),
            "Verify we're back on the products list page"
          ).toBeVisible({ timeout: 40000 })
        }
      }
    )

    await test.step(
      "Apply draft filter and verify all products are draft",
      async () => {
        await checksumAI("Click on Filter button to open filter options", () =>
          page.getByRole("button", { name: "Filters" }).click()
        )

        await checksumAI(
          "Click on Status filter option to expand status choices",
          () => page.getByRole("button", { name: "Status" }).click()
        )

        await checksumAI(
          "Click on draft checkbox to select draft status filter",
          () => page.getByText("draft", { exact: true }).click()
        )

        await checksumAI("Click Apply button to apply the draft filter", () =>
          page.getByRole("button", { name: "Apply" }).click()
        )

        await expect
          .poll(
            async () => {
              variablesStore.draftProducts = page
                .locator("tbody tr")
                .filter({ hasText: "Draft" })
              variablesStore.draftCount = await variablesStore.draftProducts.count()
              return variablesStore.draftCount
            },
            { timeout: 30000 }
          )
          .toBeGreaterThan(0)

        variablesStore.draftProducts = page
          .locator("tbody tr")
          .filter({ hasText: "Draft" })
        variablesStore.draftCount = await variablesStore.draftProducts.count()

        await expect(
          variablesStore.draftCount,
          "Verify that draft products are visible after applying draft filter"
        ).toBeGreaterThan(0)

        await expect(
          page.locator("tbody tr").filter({ hasText: "Published" }),
          "Verify no published products are visible when draft filter is applied"
        ).toHaveCount(0)
      }
    )

    await test.step(
      "Apply published filter and verify all products are published",
      async () => {
        await checksumAI(
          "Click on Filter button to reopen filter options",
          () => page.getByRole("button", { name: "Filters" }).click()
        )

        await checksumAI(
          "Click on published checkbox to select published status filter",
          () => page.getByText("published", { exact: true }).click()
        )

        await checksumAI("Uncheck draft checkbox to clear draft filter", () =>
          page.getByText("draft", { exact: true }).click()
        )

        await checksumAI(
          "Click Apply button to apply the published filter",
          () => page.getByRole("button", { name: "Apply" }).click()
        )

        await expect
          .poll(
            async () => {
              variablesStore.publishedProducts = page
                .locator("tbody tr")
                .filter({ hasText: "Published" })
              variablesStore.publishedCount = await variablesStore.publishedProducts.count()
              return variablesStore.publishedCount
            },
            { timeout: 30000 }
          )
          .toBeGreaterThan(0)

        variablesStore.publishedProducts = page
          .locator("tbody tr")
          .filter({ hasText: "Published" })
        variablesStore.publishedCount = await variablesStore.publishedProducts.count()

        await expect(
          variablesStore.publishedCount,
          "Verify that published products are visible after applying published filter"
        ).toBeGreaterThan(0)

        await expect(
          page.locator("tbody tr").filter({ hasText: "Draft" }),
          "Verify no draft products are visible when published filter is applied"
        ).toHaveCount(0)
      }
    )

    await test.step(
      "Clear filters and verify all products are visible",
      async () => {
        await checksumAI(
          "Click on Filter button to reopen filter options",
          () => page.getByRole("button", { name: "Filters" }).click()
        )

        await checksumAI(
          "Uncheck published checkbox to clear published filter",
          () => page.getByText("published", { exact: true }).click()
        )

        await checksumAI("Click Apply button to clear all filters", () =>
          page.getByRole("button", { name: "Apply" }).click()
        )

        await expect
          .poll(
            async () => {
              variablesStore.totalCount = await page.locator("tbody tr").count()
              return variablesStore.totalCount
            },
            { timeout: 30000 }
          )
          .toBeGreaterThan(0)
      }
    )
  }
)
