/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init()

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:


1. Verify that a product row is in draft mode
2. Use compoundSelection to click the three dots in a product row that is in draft mode.

*/

test(defineChecksumTest("Publish a product", "SyHTs"), async ({ page }) => {
  await login(page)
  await checksumAI("Navigate to start URL", () =>
    page.goto("/a/products", { waitUntil: "domcontentloaded" })
  )
  await checksumAI(
    "Click on the three dots menu of a product in draft mode",
    () => page.checksumSelector("ji8dR").getByText("Skin Beauty Serum").click()
  )
  await expect(
    page.getByRole("button", { name: "Publish" }),
    "Verify Publish button appears"
  ).toBeVisible()
  await checksumAI("Click on the Publish button", () =>
    page
      .checksumSelector("Jzw88")
      .getByRole("button", { name: "Publish" })
      .click()
  )
})
