/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init()

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Use the checksumAI() to wrap newly created actions.
2. Create new steps not included in the original test spec, detailed below.
3. Open a new tab and use the getPage() method to get the new page with the Checksum extensions.
4. Use reauthenticate to login as a different user (test2@test.com, 1234)
5. Use REPL for this test.

*/

test(
  defineChecksumTest(
    "Add product and login as a different user on a new tab",
    "6Fwmv"
  ),
  async ({ page }) => {
    await login(page)

    // Add The following steps to the test:
    // 1. Navigate to the product page using a relative URL.
    // 2. Create a new product
    // 3. Open a new Checksum page.
    // 4. Login as a different user (test2@test.com, 1234) using reauthenticate
    // 5. Verify the product is displayed in the table.
  }
)
