/* Checksum.ai autogenerated test */
import { init, IVariablesStore } from "@checksum-ai/runtime"
const {
  test,
  defineChecksumTest,
  login,
  expect,
  checksumAI,
  getEnvironment,
} = init()

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Use the checksumAI() to wrap newly created actions. (https://docs.google.com/document/d/1N9XNM8iKTVgUSnRV2ARGi_6lpVo3f2FCaa9pJ_GMU6Q/edit#heading=h.r1w5ax6eew51)
2. Create new steps not included in the original test spec, detailed below.
3. Open a new tab and use the getPage() method to get the new page with the Checksum extensions. (https://docs.google.com/document/d/1N9XNM8iKTVgUSnRV2ARGi_6lpVo3f2FCaa9pJ_GMU6Q/edit#heading=h.teojoel32g5o)
4. Use reauthenticate to login as a different user (test2@test.com, 1234) (https://docs.google.com/document/d/1N9XNM8iKTVgUSnRV2ARGi_6lpVo3f2FCaa9pJ_GMU6Q/edit#heading=h.3k6nlz4zu1bm)
5. Use REPL for this test. (https://docs.google.com/document/d/1N9XNM8iKTVgUSnRV2ARGi_6lpVo3f2FCaa9pJ_GMU6Q/edit#heading=h.q2653rt38xj5)

*/

test.describe(() => {
  const { environment, login: loginTest2 } = getEnvironment({
    userRole: "admin",
  })
  test.use({ baseURL: environment.baseURL })

  test(
    defineChecksumTest(
      "Add product and login as a different user on a new tab",
      "6Fwmv"
    ),
    async ({
      page,
      variablesStore,
    }: {
      page
      variablesStore: IVariablesStore
    }) => {
      await login(page)

      await expect(
        page.getByText("Welcome back! It's great to see you"),
        "Verify we're not on login page anymore"
      ).not.toBeVisible({ timeout: 25000 })

      await test.step("Navigate to products page", async () => {
        await checksumAI("Navigate to products page", () =>
          page.goto("/a/products", { waitUntil: "domcontentloaded" })
        )

        await expect(
          page.getByRole("button", { name: "New Product" }),
          "Verify the New Product button is visible on products page"
        ).toBeVisible({ timeout: 25000 })
      })

      await test.step("Create a new product with default user", async () => {
        await checksumAI(
          "Click on New Product button to create a product",
          () => page.getByRole("button", { name: "New Product" }).click()
        )

        await expect(
          page.getByPlaceholder("Winter Jacket"),
          "Verify we're on the product creation page"
        ).toBeVisible({ timeout: 25000 })

        variablesStore.productTitle = `cktest-${Date.now()}-multi-user-test`

        await checksumAI(
          "Fill product title field with unique product name",
          () =>
            page
              .getByPlaceholder("Winter Jacket")
              .fill(variablesStore.productTitle)
        )

        await checksumAI(
          "Fill product subtitle field with descriptive text",
          () =>
            page
              .getByPlaceholder("Warm and cozy...")
              .fill(`${variablesStore.productTitle} - Multi-user test product`)
        )

        await checksumAI(
          "Fill product description field with detailed information",
          () =>
            page
              .getByPlaceholder("A warm and cozy jacket...")
              .fill(
                `${variablesStore.productTitle} - This product was created to test multi-user login functionality`
              )
        )

        await expect(
          page.getByRole("button", { name: "Publish product" }),
          "Verify Publish product button is enabled after filling form"
        ).toBeEnabled({ timeout: 25000 })

        await checksumAI(
          "Click Publish product button to publish the product",
          () => page.getByRole("button", { name: "Publish product" }).click()
        )

        await expect(
          page.getByRole("button", { name: "Back to Products" }),
          "Verify Back to Products button is visible"
        ).toBeVisible({ timeout: 25000 })

        await checksumAI("Navigate back to products page", () =>
          page.getByRole("button", { name: "Back to Products" }).click()
        )

        await expect(
          page.getByRole("button", { name: "New Product" }),
          "Verify we're back on the products list page"
        ).toBeVisible({ timeout: 40000 })
      })

      await test.step(
        "Open a new tab and login as test2@test.com user",
        async () => {
          variablesStore.newPage = await page.context().newPage()

          await checksumAI(
            "Login as test2@test.com user in the new tab",
            async () => {
              await loginTest2(variablesStore.newPage)
            }
          )

          await expect(
            variablesStore.newPage.getByText(
              "Welcome back! It's great to see you"
            ),
            "Verify test2@test.com user is logged in successfully"
          ).not.toBeVisible({ timeout: 25000 })
        }
      )

      await test.step("Navigate to products page in new tab", async () => {
        await checksumAI("Navigate to products page in new tab", () =>
          variablesStore.newPage.goto("/a/products", {
            waitUntil: "domcontentloaded",
          })
        )

        await expect(
          variablesStore.newPage.getByRole("button", { name: "New Product" }),
          "Verify the New Product button is visible on products page for test2@test.com user"
        ).toBeVisible({ timeout: 25000 })
      })

      await test.step("Wait for products table to load", async () => {
        await expect
          .poll(
            async () => {
              return await variablesStore.newPage.locator("tbody tr").count()
            },
            { timeout: 30000 }
          )
          .toBeGreaterThan(0)
      })

      await test.step("Find and verify product row", async () => {
        variablesStore.productRow = variablesStore.newPage
          .locator("tbody tr")
          .filter({ hasText: variablesStore.productTitle })
        variablesStore.productRowExists =
          (await variablesStore.productRow.count()) > 0
      })

      await test.step(
        "Verify product visibility for test2@test.com user",
        async () => {
          await expect(
            variablesStore.newPage
              .locator("tbody tr")
              .filter({ hasText: variablesStore.productTitle }),
            "Verify the created product is visible in the table for test2@test.com user"
          ).toBeVisible({ timeout: 25000 })
        }
      )
    }
  )
})
