/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime"
const { test, defineChecksumTest, login, expect, checksumAI } = init()

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Select a product row that does not have cktest (so it's not created by checksum and will not be deleted by another test)
2. Verify the inventory data is correct (assume it'll stay the same)
3. To prevent cases where the test fails because the product moves to the 2nd page, filter the table to only show the product we're testing.
*/

test(
  defineChecksumTest("Verify that inventory data is correct", "3T24w"),
  async ({ page }) => {
    await login(page)
    await checksumAI("Navigate to start URL", () =>
      page.goto("/a/products", { waitUntil: "domcontentloaded" })
    )
    await checksumAI("Click on a product row", () =>
      page
        .checksumSelector("qhzwg")
        .getByRole("row", { name: "Freckle Treatment Cream- 15gm" })
        .click()
    )
  }
)
