/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

test(defineChecksumTest("Publish a product", "SyHTs"), async ({ page }) => {
  await login(page);
  await checksumAI("Navigate to start URL", () =>
    page.goto("/a/products", { waitUntil: "domcontentloaded" })
  );
  await checksumAI(
    "Click on the three dots menu of a product in draft mode",
    () => page.checksumSelector("ji8dR").getByText("Skin Beauty Serum").click()
  );
  await expect(
    page.getByRole("button", { name: "Publish" }),
    "Verify Publish button appears"
  ).toBeVisible();
  await checksumAI("Click on the Publish button", () =>
    page
      .checksumSelector("Jzw88")
      .getByRole("button", { name: "Publish" })
      .click()
  );
});
