/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

test(
  defineChecksumTest("Verify that inventory data is correct", "3T24w"),
  async ({ page }) => {
    await login(page);
    await checksumAI("Navigate to start URL", () =>
      page.goto("/a/products", { waitUntil: "domcontentloaded" })
    );
    await checksumAI("Click on a product row", () =>
      page
        .checksumSelector("qhzwg")
        .getByRole("row", { name: "Freckle Treatment Cream- 15gm" })
        .click()
    );
  }
);
