/* Checksum.ai autogenerated test */
import { init, IVariablesStore } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

/*

PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Ensure to use variablesStore to store the product name and description. ie: variablesStore.productName = "cktest-todaysdate" (this removes variable scope issues)
2. Ensure elements are created using a dynamic approach with Date.now() but use "cktest" to ensure we know the add came from one of our tests.
3. Assert the product was created successfully.
4. When asserting #2, implement a solution that takes into consideration it may not be visible on the first page load (pagination) ie: use the search bar to filter the product or go page by page until found.
5. Also, once found, verify the product details match the values used during creation.

*/

test(
  defineChecksumTest("Add a product", "78eGZ"),
  async ({
    page,
    variablesStore,
  }: {
    page;
    variablesStore: IVariablesStore;
  }) => {
    await login(page);
    await page.goto("/", { waitUntil: "domcontentloaded" });
    await checksumAI("Click on products button", () =>
      page
        .checksumSelector("FBnYK")
        .getByRole("link", { name: "Products" })
        .click()
    );
    await checksumAI("Click on new product button", () =>
      page
        .checksumSelector("x2t44")
        .getByRole("button", { name: "New Product" })
        .click()
    );
    variablesStore.titleValue = "cktest-todaysdate";
    await checksumAI("Fill title with random string", async () => {
      await page
        .checksumSelector("J6hvu")
        .getByPlaceholder("Winter Jacket")
        .clear();
      await page
        .checksumSelector("J6hvu")
        .getByPlaceholder("Winter Jacket")
        .pressSequentially(variablesStore.titleValue);
    });
    variablesStore.subtitleValue = "ck-subtitle-todaysdate";
    await checksumAI("Fill subtitle with random string", async () => {
      await page
        .checksumSelector("xSCc4")
        .getByPlaceholder("Warm and cozy...")
        .clear();
      await page
        .checksumSelector("xSCc4")
        .getByPlaceholder("Warm and cozy...")
        .pressSequentially(variablesStore.subtitleValue);
    });
    variablesStore.descriptionValue = "this is a test description";
    await checksumAI(
      'Fill description with "this is a test description"',
      async () => {
        await page
          .checksumSelector("oBOdk")
          .getByPlaceholder("A warm and cozy jacket...")
          .clear();
        await page
          .checksumSelector("oBOdk")
          .getByPlaceholder("A warm and cozy jacket...")
          .pressSequentially(variablesStore.descriptionValue);
      }
    );
    await checksumAI("Click on Publish Product button", () =>
      page
        .checksumSelector("te348")
        .getByRole("button", { name: "Publish product" })
        .click()
    );
    await checksumAI("Click back button", () =>
      page
        .checksumSelector("njoFW")
        .getByRole("button", { name: "Back to Products" })
        .click()
    );
  }
);
