/* Checksum.ai autogenerated test */
import { init, IVariablesStore } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

test(
  defineChecksumTest("Add a product", "78eGZ"),
  async ({
    page,
    variablesStore,
  }: {
    page;
    variablesStore: IVariablesStore;
  }) => {
    await login(page);
    await page.goto("/", { waitUntil: "domcontentloaded" });
    await checksumAI("Click on products button", () =>
      page
        .checksumSelector("FBnYK")
        .getByRole("link", { name: "Products" })
        .click()
    );
    await checksumAI("Click on new product button", () =>
      page
        .checksumSelector("x2t44")
        .getByRole("button", { name: "New Product" })
        .click()
    );
    variablesStore.titleValue = "cktest-todaysdate";
    await checksumAI("Fill title with random string", async () => {
      await page
        .checksumSelector("J6hvu")
        .getByPlaceholder("Winter Jacket")
        .clear();
      await page
        .checksumSelector("J6hvu")
        .getByPlaceholder("Winter Jacket")
        .pressSequentially(variablesStore.titleValue);
    });
    variablesStore.subtitleValue = "ck-subtitle-todaysdate";
    await checksumAI("Fill subtitle with random string", async () => {
      await page
        .checksumSelector("xSCc4")
        .getByPlaceholder("Warm and cozy...")
        .clear();
      await page
        .checksumSelector("xSCc4")
        .getByPlaceholder("Warm and cozy...")
        .pressSequentially(variablesStore.subtitleValue);
    });
    variablesStore.descriptionValue = "this is a test description";
    await checksumAI(
      'Fill description with "this is a test description"',
      async () => {
        await page
          .checksumSelector("oBOdk")
          .getByPlaceholder("A warm and cozy jacket...")
          .clear();
        await page
          .checksumSelector("oBOdk")
          .getByPlaceholder("A warm and cozy jacket...")
          .pressSequentially(variablesStore.descriptionValue);
      }
    );
    await checksumAI("Click on Publish Product button", () =>
      page
        .checksumSelector("te348")
        .getByRole("button", { name: "Publish product" })
        .click()
    );
    await checksumAI("Click back button", () =>
      page
        .checksumSelector("njoFW")
        .getByRole("button", { name: "Back to Products" })
        .click()
    );
  }
);
