/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

test(defineChecksumTest("Add a product", "j1AMo"), async ({ page }) => {
  await login(page);
  await page
    .checksumSelector("DiSpH")
    .getByRole("link", { name: "Pricing" })
    .click();
  await page
    .checksumSelector("Cv3yR")
    .getByRole("link", { name: "NativeDialog" })
    .click();
});
