/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

test(defineChecksumTest("Delete a product", "G8RlA"), async ({ page }) => {
  await login(page);
  await page.goto("/", { waitUntil: "domcontentloaded" });
  await checksumAI("Click on products button", () =>
    page
      .checksumSelector("eQtTT")
      .getByRole("link", { name: "Products" })
      .click()
  );
  await checksumAI("Click on a product", () =>
    page
      .checksumSelector("xLAhI")
      .getByRole("cell", { name: "Non-Alcoholic Concentrated" })
      .getByRole("img")
      .click()
  );
  await checksumAI("Click on 3 dot menu next to product name", () =>
    page.checksumSelector("sus9U").locator("#radix-42").click()
  );
  await checksumAI("Click on Delete option", () =>
    page
      .checksumSelector("IH40z")
      .getByRole("button", { name: "Delete" })
      .click()
  );
  await checksumAI("Click on 'Yes, confirm delete'", () =>
    page
      .checksumSelector("LT9Un")
      .getByRole("button", { name: "Yes, confirm" })
      .click()
  );
});
