/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

test(defineChecksumTest("Delete a product", "klHCH"), async ({ page }) => {
  await login(page);
  await page
    .checksumSelector("iqyq6")
    .getByRole("link", { name: "Discounts" })
    .click();
  await page
    .checksumSelector("waLdq")
    .getByRole("link", { name: "Products" })
    .click();
});
