/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Ensure to use variablesStore to store the product name and description. ie: variablesStore.productName = "cktest-todaysdate" (this removes variable scope issues)
2. Verify the app state -- Are there any pre-conditions to be met before running this test? ie: Are there products to delete? Use a try/catch statement.
3. Take an approach that is robust -- ie; picking the first element in the product list and deleting it (since it is safe to assume products will be listed in the same order for all tests)
4. After deleting -- verify the product was removed by using a regular expression to match the product name.

*/

test(defineChecksumTest("Delete a product", "G8RlA"), async ({ page, variablesStore }) => {
  await login(page);
  await page.goto("/", { waitUntil: "domcontentloaded" });
  await checksumAI("Click on products button", () =>
    page
      .checksumSelector("eQtTT")
      .getByRole("link", { name: "Products" })
      .click()
  );
  await checksumAI("Click on a product", () =>
    page
      .checksumSelector("xLAhI")
      .getByRole("cell", { name: "Non-Alcoholic Concentrated" })
      .getByRole("img")
      .click()
  );
  await checksumAI("Click on 3 dot menu next to product name", () =>
    page.checksumSelector("sus9U").locator("#radix-42").click()
  );
  await checksumAI("Click on Delete option", () =>
    page
      .checksumSelector("IH40z")
      .getByRole("button", { name: "Delete" })
      .click()
  );
  await checksumAI("Click on 'Yes, confirm delete'", () =>
    page
      .checksumSelector("LT9Un")
      .getByRole("button", { name: "Yes, confirm" })
      .click()
  );
});
