/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Ensure to use variablesStore to store the product name and description. ie: variablesStore.productName = "cktest-todaysdate" (this removes variable scope issues)
2. When setting the filter, ensure only the products that match the filter are displayed on the page.
3. Use Checksum built in method - page.compoundSelector() to get the relevant elements for verification.
3. Verify the state -- if testing for a filter with the value "draft", ensure a products with draft is displayed and if not - edit a product to be a draft before filtering

*/

test(defineChecksumTest("Filter for a product", "Roi2Q"), async ({ page, variablesStore }) => {
  await login(page);
  await page.goto("/", { waitUntil: "domcontentloaded" });
  await checksumAI("Click on products", () =>
    page
      .checksumSelector("dilYE")
      .getByRole("link", { name: "Products" })
      .click()
  );
  await checksumAI("Click the 3 dots next to product card", () =>
    page.checksumSelector("tioYO").locator("#radix-11").click()
  );
  await checksumAI("Click unpublish", () =>
    page
      .checksumSelector("GEFM7")
      .getByRole("button", { name: "Unpublish" })
      .click()
  );
  await checksumAI("Click on Filter button", () =>
    page
      .checksumSelector("IxPkN")
      .getByRole("button", { name: "Filters" })
      .click()
  );
  await checksumAI("Click on status checkbox", () =>
    page
      .checksumSelector("vECUj")
      .getByRole("button", { name: "Status" })
      .click()
  );
  await checksumAI("Click on draft checkbox", () =>
    page.checksumSelector("2sSKi").getByText("draft", { exact: true }).click()
  );
  await checksumAI("Click Apply button", () =>
    page
      .checksumSelector("vctsb")
      .getByRole("button", { name: "Apply" })
      .click()
  );
});
