/* Checksum.ai autogenerated test */
import { init } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

test(
  defineChecksumTest("Open a new browser tab", "6Fwmv"),
  async ({ page }) => {
    await login(page);
    await page.goto("/", { waitUntil: "domcontentloaded" });
    await checksumAI("Navigate to https://www.google.com/", () =>
      page.goto("https://www.google.com/", { waitUntil: "domcontentloaded" })
    );
  }
);
