/* Checksum.ai autogenerated test */
import { init, IVariablesStore } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

/*
PRINCIPLES TO LEARN & IMPLEMENT WHEN EDITING THIS TEST:

1. Ensure to use variablesStore to store the product name and description. ie: variablesStore.productName = "cktest-todaysdate" (this removes variable scope issues)
2. Verify the app state -- Are there any pre-conditions to be met before running this test? ie: Are there products to search for? Use a try/catch statement.
3. Use Checksum built in method - page.compoundSelector() to get the relevant elements for verification. (visit the readme for more details about this method ./checksum/README.md)
4. Verify the search results only contain the products that match the search criteria.

*/

test(
  defineChecksumTest("Search for a product", "iOCS5"),
  async ({
    page,
    variablesStore,
  }: {
    page;
    variablesStore: IVariablesStore;
  }) => {
    await login(page);
    await page.goto("/", { waitUntil: "domcontentloaded" });
    await checksumAI("Click on products", () =>
      page
        .checksumSelector("m1urH")
        .getByRole("link", { name: "Products" })
        .click()
    );
    variablesStore.searchValue = "Non-Alcoholic";
    await checksumAI("Search for a product", async () => {
      await page.checksumSelector("POwjT").getByPlaceholder("Search").clear();
      await page
        .checksumSelector("POwjT")
        .getByPlaceholder("Search")
        .pressSequentially(variablesStore.searchValue);
    });
  }
);
