/* Checksum.ai autogenerated test */
import { init, IVariablesStore } from "@checksum-ai/runtime";
const { test, defineChecksumTest, login, expect, checksumAI } = init();

test(
  defineChecksumTest("Search for a product", "iOCS5"),
  async ({
    page,
    variablesStore,
  }: {
    page;
    variablesStore: IVariablesStore;
  }) => {
    await login(page);
    await page.goto("/", { waitUntil: "domcontentloaded" });
    await checksumAI("Click on products", () =>
      page
        .checksumSelector("m1urH")
        .getByRole("link", { name: "Products" })
        .click()
    );
    variablesStore.searchValue = "Non-Alcoholic";
    await checksumAI("Search for a product", async () => {
      await page.checksumSelector("POwjT").getByPlaceholder("Search").clear();
      await page
        .checksumSelector("POwjT")
        .getByPlaceholder("Search")
        .pressSequentially(variablesStore.searchValue);
    });
  }
);
